public class SystemDebugListasDePersonas 
{

persona kike = new persona('kike',20 ,'M' ,1.70);
persona Nerea = new persona('Nerea',20 ,'F' , 1.70);
persona yessi = new persona('Yessi',26 ,'F' ,1.90);
persona sese = new persona('sese',54 ,'F' , 1.68);
persona chicha = new persona('chicha',85 ,'F' ,1.65);
persona Marga = new persona('Marga',64 ,'F' ,1.72);
persona Avelino = new persona('Avelino',68 ,'M' ,1.80);
persona carlos = new persona('Carlos',57 ,'M' ,1.86);

list <persona> ListaGente = new list <persona> {kike , nerea , yessi , sese , chicha , marga , avelino , carlos };
    

// ListaDePersonas.listaGente(ListaGente);
    
}